### ISSUE TITLE
YoloV8, Hough lines, ONNX support?

### ISSUE THREAD

**Issue by dancixx** [LdDl/rust-road-traffic#17]
Hey there,

First off, hats off for creating such a fantastic product! 🚀

Just a couple of thoughts:

Any chance we could see support for newer Yolo versions or importing onnx files?
How about integrating Hough lines detection to save us from manually drawing those boxes?

**Comment by LdDl** [comment]
Hello!
Thanks for very kind words)

Yeah, I'm planning to move to full ONNX support since even v3/v4 version of YOLO could be converted into it and ONNX is considered to be standart-_ish_ in industry.

What about YOLOv5/YOLOv7/YOLOv8 and other [Ultralytics](https://github.com/ultralytics/ultralytics) stuff?
Currently I'm learning YOLOv8 Nano variation and prototyping in Python inference for it via OpenCV (since I do no want to introduce Pytorch here) and have a bit struggling to represent class scores, but it is on my way. Of course, the training part is done in Pytorch and I'll create another repo similar to [yolo_vehicles](https://github.com/LdDl/yolo_vehicles)

And the last part: **_Hough lines_**
I assume that user should markup detection region by his own hands, since there could not be roadmarkup on the road at all. **_Hough lines_** could be helpful, but only if it is done not by detection software, but with UI side of it

**Comment by dancixx** [comment]
Yesterday I tried to refactor the project using onnx `opencv::dnn:read_net_from_onnx`, it seemed everything worked fine but the inference did not happen. I am not sure if that is possible right now because maybe the Yolo model contains such layers which are not supported currently in opencv dnn module, so maybe should use some other different NN framework like rust tensorflow binding or tch-rs. I checked Candle, but there is an open issue that the inference is much slower than onnxruntime or pytorch in Python.

**Comment by LdDl** [comment]
I'm back here again.

So, I've tested ONNX for v8 and it works good I believe, but inference functions is different from traditional YOLO-family.
https://github.com/LdDl/object-detection-opencv-rust/blob/master/src/model_ultralytics.rs#L155


Also, I've noticed that OpenCV 4.6.0 is not working with YOLOv8. Therefore I've switched to OpenCV 4.7.0

**Comment by dancixx** [comment]
Thanks for the update. I will check it, maybe to join as a contributor for the package. :)

**Comment by LdDl** [comment]
Another update (2023.12.04):
Just bumped main branch with integration of model trait, so we are free to use either traditional YOLO or Ultralytics one.
But, be aware: OpenCV 4.6.0 is not working with YOLOv8.

**Comment by LdDl** [comment]
I think we can consider this issue to be closed.
Results:
- YoloV8 seems to work
- Hough line is up to end-user (front-end/CLI settings manager)
